name: bigheadfarm
favicon: null
layout_spectrum: 0.36882
typography_spectrum: 0.18977
title: 'Big Head Farm, a certified organic farm'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#22201d'
    - '#a2d48a'
    - '#7f7f7f'
    - '#278547'
  brandStrength: 0.5
  lightness: 0.3164179299492389
  saturation: 0.9265667572617531
  rhythmicContrast: 0.10901988530531526
purpose: []
